name: flutter_presentation
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1
environment:
  sdk: '>=3.0.3 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  flutter_deck: ^0.10.1
  flutter_shader_snap: ^0.0.3
  flutter_svg: ^2.0.13
  tflite_flutter: ^0.10.4
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/models/
    - assets/videos/
  shaders:
    - packages/flutter_shader_snap/shaders/split_snap_effect_shader.glsl
    - packages/flutter_shader_snap/shaders/split_reversed_snap_effect_shader.glsl
