
name: flutter_demo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  camera: ^0.10.6
  flutter:
    sdk: flutter
  image: ^4.3.0
  image_gallery_saver: '^2.0.3'
  path_provider: ^2.1.5
  screenshot: ^3.0.0
  share_plus: ^10.1.1
  tflite_flutter: ^0.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/images/
